### ISSUE TITLE
商品模块 -- 主页

### ISSUE THREAD

**Issue by ycdeng** [zhenailuoye1/mission#10]
主要是商品的增删查改

**Comment by ycdeng** [comment]
初始版本
1.  做一个列表, 把所有的商品展示出来; 必须有翻页功能, 每页5个
2.  在页面顶部有按钮: 新建商品, 查找商品(根据商品名)
3.   每一个商品有删除, 修改

先做出界面, 具体功能一步步来

**Comment by zhenailuoye1** [comment]
2里面的增加和3里面的新建什么区别

**Comment by ycdeng** [comment]
描述已修改
