### ISSUE TITLE
如何在flask里操作数据库

### ISSUE THREAD

**Issue by zhenailuoye1** [zhenailuoye1/mission#2]
使用sqlite3，怎样把注册页面传过来的账号、密码、邮箱保存到数据库里面，并且如何读取数据库里已有的数据 @ycdeng

**Comment by ycdeng** [comment]
http://docs.jinkan.org/docs/flask/tutorial/

既然自己开始了, 那就仔细看完这种教程, 照着教程一步步做下去.
