### ISSUE TITLE
登陆页问题

### ISSUE THREAD

**Issue by ycdeng** [zhenailuoye1/mission#22]
我们需要做的是照抄别人的网站.

而不是自己设计, 只有完整的照别人做一个, 才能体会到其中的难处, 如果遇到不好做的就回避, 那没任何意义...

另外有如下问题
1. 当浏览器水平拖拉时, 知乎能保证主要内容显示在正中心, 是相应式的
2. 背景图在更大屏幕下的显示仍然有问题
3. 颜色风格完全不一致

**Comment by ycdeng** [comment]
另外在以后的工作中有个最常见的场景:
xxx有这个效果, 我们也要..

**Comment by zhenailuoye1** [comment]
2、显示有问题是什么意思

**Comment by ycdeng** [comment]
没有铺满整个页面,
