### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by ycdeng** [zhenailuoye1/mission#6]
百度搜索, mvc设计模式

参考问题:
1. 用自己的话描述,M,V,C 分别是什么;
2. 结合已有flask代码, 所写与mvc对应上号

**Comment by zhenailuoye1** [comment]
1、model、view、controller，view从字面意义来看应该是指用户可以看见的内容，model应该是后台处理的部分，controller的话则类似于胶水，将model和view粘起来起到衔接的作用，从而使用户能够正常应用。
2、就目前的代码来看，html，css属于view，sqlite属于model，js的事件监听发起的request，传给flask路由参数、处理后的response应该属于controller
