### ISSUE TITLE
管理系统 -- 主页

### ISSUE THREAD

**Issue by ycdeng** [zhenailuoye1/mission#9]
做一个侧边栏, 参考qq邮箱..
样式使用bootstrap

目前无其他功能, 先放上以下模块
1. 商品管理
2. 用户管理
3. 订单管理

点击时先跳到一个空白页面, 但必须不一样..

在侧边栏必须能显示看出当前在哪个页面

**Comment by zhenailuoye1** [comment]
这三个模块是要三个页面么。。。

**Comment by zhenailuoye1** [comment]
已添加到主页
